package permissions.dispatcher.processor.util;

public final class Constants {
    public static final String FILE_COMMENT = "This file was generated by PermissionsDispatcher. Do not modify!";
    public static final String GEN_CLASS_SUFFIX = "PermissionsDispatcher";
    public static final String GEN_REQUESTCODE_PREFIX = "REQUEST_";
    public static final String GEN_PERMISSION_PREFIX = "PERMISSION_";
    public static final String GEN_PENDING_PREFIX = "PENDING_";
    public static final String GEN_WITHCHECK_SUFFIX = "WithCheck";
    public static final String GEN_PERMISSIONREQUEST_SUFFIX = "PermissionRequest";
    public static final String PACKAGE_NAME = "permissions.dispatcher";
}
